# Generated by Django 4.0.5 on 2023-03-04 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name_plural': 'Api Keys',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=9999)),
            ],
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ts', models.IntegerField()),
                ('day_temp', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('night_temp', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('weather', models.CharField(max_length=255)),
                ('weather_desc', models.CharField(max_length=255)),
                ('fetched', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ts', models.IntegerField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('weather', models.CharField(max_length=255)),
                ('weather_desc', models.CharField(max_length=255)),
                ('fetched', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
    ]
