# Generated by Django 4.0.5 on 2023-03-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('limit', models.IntegerField()),
                ('currentLimit', models.IntegerField()),
                ('resetDate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'API Limit',
            },
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='fetched',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='fetched',
            field=models.DateField(),
        ),
    ]
