# Generated by Django 4.0.5 on 2023-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apilimit_alter_currentweather_fetched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=9999),
            preserve_default=False,
        ),
    ]
