# Generated by Django 4.0.5 on 2023-03-05 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='fetched',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='fetched',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
