# Generated by Django 4.0.5 on 2023-03-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_currentweather_fetched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='ts',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='ts',
            field=models.BigIntegerField(),
        ),
    ]
