# Generated by Django 4.0.5 on 2023-03-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_currentweather_ts_alter_dailyforecast_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='dailyforecast',
            name='ts',
        ),
        migrations.AddField(
            model_name='currentweather',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
