# Generated by Django 4.0.5 on 2023-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_currentweather_ts_remove_dailyforecast_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='temp_feels_like',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
